# Generated by Django 6.1 on 2026-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_latitude_user_location_permission_granted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='user',
            name='location_source',
            field=models.CharField(blank=True, choices=[('gps', 'GPS'), ('manual', 'Manual')], max_length=10, null=True),
        ),
    ]
