# Generated by Django 6.1 on 2026-08-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_user_id_f0e72c_idx',
            old_name='notificatio_user_id_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notificatio_recipie_created_idx',
        ),
    ]
