# Generated by Django 6.0.4 on 2026-05-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_worker_bio_and_work_images'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='workers_boo_worker__c394ed_idx',
            old_name='workers_boo_worker__4868fe_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='workers_boo_custome_d558da_idx',
            old_name='workers_boo_custome_2de3c6_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='workers_boo_schedul_a4281d_idx',
            old_name='workers_boo_schedul_04136b_idx',
        ),
    ]
