# Generated by Django 6.0.4 on 2026-05-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_conversation_message_bookingreview'),
        ('workers', '0005_rename_workers_boo_worker__4868fe_idx_workers_boo_worker__c394ed_idx_and_more'),
    ]

    operations = [
    ]
