# Generated by Django 6.1 on 2026-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_booking_location_permission_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_location_source',
            field=models.CharField(blank=True, choices=[('saved', 'Saved'), ('gps', 'GPS'), ('manual', 'Manual')], max_length=10, null=True),
        ),
    ]
