// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69LywOi3TkLj0p5oaeci07MgdynYjNmU',
    appId: '1:460379657818:web:e68b2bb8881989a9be6a63',
    messagingSenderId: '460379657818',
    projectId: 'workerapp-c442a',
    authDomain: 'workerapp-c442a.firebaseapp.com',
    storageBucket: 'workerapp-c442a.firebasestorage.app',
    measurementId: 'G-NW1VMB1V34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-LMkONe342gBBrIS68T-zFnCYWePNkc',
    appId: '1:460379657818:android:c56bdecd0e88378dbe6a63',
    messagingSenderId: '460379657818',
    projectId: 'workerapp-c442a',
    storageBucket: 'workerapp-c442a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8w1zsGVsa5lPsjtZKiyuNuMTGBV_LGOc',
    appId: '1:460379657818:ios:b37784f3ab0edbd9be6a63',
    messagingSenderId: '460379657818',
    projectId: 'workerapp-c442a',
    storageBucket: 'workerapp-c442a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8w1zsGVsa5lPsjtZKiyuNuMTGBV_LGOc',
    appId: '1:460379657818:ios:b37784f3ab0edbd9be6a63',
    messagingSenderId: '460379657818',
    projectId: 'workerapp-c442a',
    storageBucket: 'workerapp-c442a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB69LywOi3TkLj0p5oaeci07MgdynYjNmU',
    appId: '1:460379657818:web:7b0ce833eaf4fa9cbe6a63',
    messagingSenderId: '460379657818',
    projectId: 'workerapp-c442a',
    authDomain: 'workerapp-c442a.firebaseapp.com',
    storageBucket: 'workerapp-c442a.firebasestorage.app',
    measurementId: 'G-N19X7HLTN9',
  );
}
